name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: pip install -r requirements.txt

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend (if applicable)
        working-directory: ./frontend
        run: |
          if [ -f package.json ] && grep -q "\"build\":" package.json; then
            npm run build
          else
            echo "No build script found, skipping build."
          fi

      - name: Zip backend
        run: zip -r backend.zip . -x "frontend/*" ".git/*" ".github/*" "backend.zip" "frontend.zip"

      - name: Zip frontend
        working-directory: ./frontend
        run: zip -r ../frontend.zip . -x "node_modules/*" ".git/*"

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: backend.zip

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: frontend.zip
